### ISSUE TITLE
FInd bugs in existing version

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/webtech#28] opened 2020-02-18 05:08 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tawishi** [comment] 2020-02-21 04:20
I would like to work on this issue.

**Comment by kaiiyer** [comment] 2020-02-21 08:10
Okay I've assigned you the issue !!

**Comment by mridubhatnagar** [comment] 2020-02-22 19:48
Just curious to know have the contributions from participants already started? As I can see task assignment and the website says contribution starts from 1st March.

**Comment by kaiiyer** [comment] 2020-02-23 11:39
Only the merged pull requests from March 1 will be considered for giving you the points. Nevertheless you can put a draft pull or get familiarized with the project till then !!

**Comment by Tawishi** [comment] 2020-02-24 09:57
How do I run the project code in VS Code ?

**Comment by kaiiyer** [comment] 2020-02-24 13:28
Fork the project and download it to your local system. Open it like any other file in VSCode. For running the code please refer the documentation. If you face any issue do report here !!

**Comment by ranjal007** [comment] 2020-02-29 18:37
I would like to work on this issue 
please assign it to me for gssoc20.

**Comment by myworkcircle** [comment] 2020-03-01 06:44
i would like to work on this issue

**Comment by kaiiyer** [comment] 2020-03-01 07:52
@ranjal007 and @myworkcircle You can work on it !!

**Comment by ashwinijha6** [comment] 2020-03-01 10:04
I would like to work on this issue

**Comment by manan-bedi2908** [comment] 2020-03-01 10:12
I would like to work on this issue

**Comment by kaiiyer** [comment] 2020-03-01 11:23
Can you wait for a few days, some folks are already working on it !

**Comment by ashwinijha6** [comment] 2020-03-01 12:49
ok

**Comment by akshatj355** [comment] 2020-03-01 16:04
I want to work on this issue.

**Comment by VibavariG** [comment] 2020-03-01 16:10
Sir, I would like to work on this issue

**Comment by koderjoker** [comment] 2020-03-06 07:43
Hi @ranjal007 @myworkcircle @ashwinijha6 @manan-bedi2908 @VibavariG since this is a general issue where you just have to find a bug, discuss it with us and then send in a pr to fix it, we've assigned it to you all to give it a go.

**Comment by arkadeepde142** [comment] 2020-03-09 15:28
I would like to work on this issue.

**Comment by FrozenGirl-spd** [comment] 2020-03-10 07:58
Can i work on the issue please?

**Comment by kaiiyer** [comment] 2020-03-10 09:30
Yeah go on !!

**Comment by gunjanverma0405** [comment] 2020-03-11 06:37
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

I am interested in this

**Comment by kaiiyer** [comment] 2020-03-11 08:16
Go on !

**Comment by poojasrinivass** [comment] 2020-03-13 22:09
I would like to work on this issue.

**Comment by Varshney200** [comment] 2020-03-14 09:54
Can I also work on this issue under gssoc?

**Comment by Gutapa** [comment] 2020-03-17 19:58
Hi guys,
I am not sure if this is a bug, but when I ran webtech for quora I got the following results
![Webtech quora](https://user-images.githubusercontent.com/20564908/76896270-8d785980-68b7-11ea-9a7c-8db92c7f2f43.png)

**Comment by Gutapa** [comment] 2020-03-17 20:02
> A quick search on google shows that they used python
>  

Nice finding but it's not a bug though !

**Comment by Gutapa** [comment] 2020-03-20 20:21
Hey @kaiiyer thanks for the clarification.
Can you further describe is this a limitation or is this an open issue?

**Comment by Gutapa** [comment] 2020-03-20 21:32
![localhost](https://user-images.githubusercontent.com/20564908/77210195-5f4c8100-6b26-11ea-8967-4289e91efbd7.png)

Localhost returns different results each time

![tplinkwifinet](https://user-images.githubusercontent.com/20564908/77207526-98cdbe00-6b1f-11ea-8c0c-91f1832e7dc6.png)

Another random anomaly not sure it it is a bug/issue.
This link is my Routers login link.
Please pardon me if this is another failed attempt as I don't have complete understanding as to how webtech does what it does. 
Any documentation/help to understand this would be much appreciated.

**Comment by kaiiyer** [comment] 2020-03-21 05:19
@koderjoker Look into it !

**Comment by rbjoshi1309** [comment] 2020-04-26 11:25
@kaiiyer Please take a look at PR #61

**Closed as completed** 2020-06-26 05:34 UTC
Labels: good first issue, beginner, no-issue-activity
